import { Camera, Globe, MousePointer, Cpu, Database, Server } from "lucide-react"

export const YourName = "NGUYEN MINH QUAN"

export const projects = [
    {
      id: "servexa-warranty-ai",
      title: "Servexa Warranty AI",
      subtitle: "Agentic AI Operation Platform",
      category: "AI Product",
      description: "AI-powered warranty operation platform with RAG-based knowledge retrieval and Copilot assistance",
      icon: Cpu,
      gradient: "from-[#01071a] via-[#000588] to-[#00d2ff]",
      hoverColors: {
        title: "group-hover:text-[#cdffe8]",
        subtitle: "group-hover:text-[#00d2ff]",
        description: "group-hover:text-[#00d2ff]",
      },
      shadowColor: "group-hover:shadow-blue-500/20",
      techStack: "React + FastAPI + LangGraph + PostgreSQL",
      projectType: "Enterprise Application",
      architectureHighlights: "Agentic Architecture, RAG Pipeline, gRPC",
      keyMetrics: "Integrated AI Copilot & Human-in-the-loop workflows",
    },
    {
      id: "readdi",
      title: "READDI",
      subtitle: "AI-powered IELTS Platform",
      category: "EdTech",
      description: "E-learning platform with AI-powered feedback and personalized learning suggestions",
      icon: Globe,
      gradient: "from-[#000588] via-purple-600 to-[#3a7bd5]",
      hoverColors: {
        title: "group-hover:text-white",
        subtitle: "group-hover:text-purple-300",
        description: "group-hover:text-purple-300",
      },
      shadowColor: "group-hover:shadow-purple-500/20",
      techStack: "Next.js + NestJS + PostgreSQL + Redis",
      projectType: "B2C Web App",
      architectureHighlights: "CSR/SSR optimization, Microservices",
      keyMetrics: "15+ responsive AI learning workflows",
    },
    {
      id: "cores",
      title: "CORES",
      subtitle: "Internal Management System",
      category: "Infrastructure",
      description: "Appliance after-sales service system for inventory tracking and warranty activation",
      icon: Server,
      gradient: "from-[#1a2a6c] via-[#b21f1f] to-[#fdbb2d]",
      hoverColors: {
        title: "group-hover:text-white",
        subtitle: "group-hover:text-[#fdbb2d]",
        description: "group-hover:text-[#fdbb2d]",
      },
      shadowColor: "group-hover:shadow-red-500/20",
      techStack: "React + .NET Core + TanStack Query",
      projectType: "Internal Tooling",
      architectureHighlights: "Role-based Permission Control",
      keyMetrics: "Optimized ASC operation workflows",
    },
    {
      id: "locknlock-asc",
      title: "LocknLock ASC",
      subtitle: "Customer Service System",
      category: "Infrastructure",
      description: "After-sales service management system supporting repair cases and accessory inventory",
      icon: Database,
      gradient: "from-[#11998e] to-[#38ef7d]",
      hoverColors: {
        title: "group-hover:text-white",
        subtitle: "group-hover:text-[#38ef7d]",
        description: "group-hover:text-[#38ef7d]",
      },
      shadowColor: "group-hover:shadow-emerald-500/20",
      techStack: "Next.js + Express + Prisma + PostgreSQL",
      projectType: "Internal Tooling",
      architectureHighlights: "Excel/PDF import-export pipeline",
      keyMetrics: "10+ frontend management screens built",
    }
  ]